### PR TITLE
Unit tests and fixes for Double & Float instances of HomTransform4

### PR DESCRIPTION
**Pull request by Rotaerk**
I've split MatrixTest into Double and Float variants, and implemented unit tests for the Double and Float instances of HomTransform4.  I also made some fixes to the instances themselves, after encountering some problems while building the unit tests.

1) I had made a mistake in the calculation of the projection matrix's z-basis; hadn't accounted for the "forward" direction being -Z, not +Z.
1) The rotateEuler matrix needed to be transposed in order to satisfy the test property:
   ```hs
   prop_rotateEuler x y z = rotateEuler x y z `approxEqD44` rotateX x %* rotateY y %* rotateZ z
   ```

Please review the test properties to ensure they meet your expectations.  If they don't, we'll need to fix both the test *and* the implementation, because all the tests currently pass.

### CODE REVIEW

**Comment by Rotaerk** [comment]
~~Hmm, hold on.  I went to use this branch of easytensor from my vulkanTest project, and it's not seeing the Double instance of HomTransform4 when Numeric.DataFrame or Numeric.Matrix are imported.  Need to figure out why the instance isn't being exported...~~

Edit:  Oops; never mind.  This was resolved by rerunning `cabal configure` in my project...

**Comment by achirkin** [comment]
Thank you very much for the effort writing tests!

A small thing: why you use 3 customized `approxEqXX` functions? Would something like this work?:
```Haskell
approxEq :: Dimensions (ds :: [Nat]) => DataFrame Double ds -> DataFrame Double ds -> Bool
approxEq a b = (eps >=) . ewfoldl @_ @'[] max 0 . abs $ a - b
```
(you may also need a `Num (DataFrame Double ds)` constraint if it is not recognized by GHC (although it should))

The `HomTransform4` changes looks plausible. Though, things like projection matrices and Euler angles 
 are sometimes defined in slightly different notations. In this library I always try to stick to the same notation as used in [OpenGL wikibooks](https://en.wikibooks.org/wiki/GLSL_Programming/Vertex_Transformations) and in GLUT library (modulo column-first layout of matrices). Do you refer to the same sources when testing the properties? Could you please give a link to a source explaining `rotateEuler` in our notation for the benefit of potential users? (as a haddock to a `HomTransform4` class definition, similar to `perspective` function)

**Comment by Rotaerk** [comment]
I initially tried making a unified `approxEq` function but couldn't figure out how to resolve the type errors.  If I write this:
```hs
approxEq :: forall (ds :: [Nat]). (Dimensions ds, Num (DataFrame Double ds)) => DataFrame Double ds -> DataFrame Double ds -> Bool
```
I get the following error:
```
test/Numeric/MatrixDoubleTest.hs:26:27: error:
    • Could not deduce (Numeric.DataFrame.Internal.Array.Class.PrimArray
                          Double (Numeric.DataFrame.Internal.Array.Family.Array Double ds))
        arising from a use of ‘ewfoldl’
      from the context: (Dimensions ds, Num (DataFrame Double ds))
        bound by the type signature for:
                   approxEq :: forall (ds :: [Nat]).
                               (Dimensions ds, Num (DataFrame Double ds)) =>
                               DataFrame Double ds -> DataFrame Double ds -> Bool
        at test/Numeric/MatrixDoubleTest.hs:25:1-130
    • In the first argument of ‘(.)’, namely ‘ewfoldl @_ @'[] max 0’
      In the second argument of ‘(.)’, namely
        ‘ewfoldl @_ @'[] max 0 . abs’
      In the expression: (eps >=) . ewfoldl @_ @'[] max 0 . abs
   |
26 | approxEq a b = (eps >=) . ewfoldl @_ @'[] max 0 . abs $ a - b
   |                           ^^^^^^^^^^^^^^^^^^^^^
```
I initially gave up at this point.  However, now I've imported the PrimArray class, and added another constraint.  I got a similar error for PrimBytes, so I did the same for that, and now I have the following working signature:

```hs
approxEq :: forall (ds :: [Nat]). (Dimensions ds, Num (DataFrame Double ds), PrimBytes (DataFrame Double ds), PrimArray Double (DataFrame Double ds)) => DataFrame Double ds -> DataFrame Double ds -> Bool
```

Is there any way to clean that up?

**Comment by Rotaerk** [comment]
And regarding the changes to the homogenous transforms:
1) I believe the perspective matrix (now) matches your ghcjs implementation.  The change just addressed a mistake that I made in the first version.  (Particularly, I assumed that "forward" was +Z, and thus the Z-basis should be `foc - cam`, or a vector pointing from camera to focus.  However, since "forward" is -Z, you have to negate that, so the Z-basis is actually a vector from focus to camera, or `cam - foc`.)
1) As for the `rotateEuler` function, my initial implementation matched your ghcjs implementation, so my revision (in which I transposed the matrix) does deviate from it.  I didn't find any information about this type of matrix on that OpenGL wikibooks page, so I had to look to other sources, particularly the Wikipedia pages on [Euler angles](https://en.wikipedia.org/wiki/Euler_angles) and [Davenport chained rotations](https://en.wikipedia.org/wiki/Davenport_chained_rotations).  Based on these articles, I concluded that `rotateEuler` should be equivalent to a sequence of "elemental rotations", but that there are many possible sequences it could take.

   I landed on the `rotateX x %* rotateY y %* rotateZ z` sequence based on experimentation, and discovering that it is equal to the transpose of the original matrix (the closest match I could find to your original implementation).  However, if there is a sensible sequence that is equal to the original matrix, then we can revert the implementation and change the test.  I haven't identified what that sequence would be, though.

   In fact, I just tested more exhaustively, by generating a list of every possible sequence of X-, Y-, and Z- rotations, (i.e. [[rotateX, rotateX, rotateX], [rotateX, rotateX, rotateY], [rotateX, rotateX, rotateZ], [rotateX, rotateY, rotateX], ...]), and then comparing the resulting matrix of each sequence to the result of rotateEuler.  No sequence matched the result of the original implementation, and only one sequence matched the result of the transposed implementation:  [rotateZ, rotateY, rotateX], which is the sequence represented by the above property.

   Also, if you look at the "Rotation Matrix" section of the [Euler angles](https://en.wikipedia.org/wiki/Euler_angles) page, it has a table of matrices for all the different sequences.  The new, transposed implementation of `rotateEuler` matches the X<sub>1</sub>Y<sub>2</sub>Z<sub>3</sub> matrix under "Tait-Bryan angles".  The original implementation doesn't seem to match any of them.

**Comment by achirkin** [comment]
Yes, easytensor class inheritance is still far from perfect :( but you don't need to copy the same code three times at least :) 

Sorry, I did not mean to say your changes to the functions of `HomTransform4` are incorrect. I just wanted to say that matrix transformations were a hassle for me every time I implemented them, and I certainly could have errors in there. I've updated documentation of `rotateEuler` to match your findings.

**Comment by Rotaerk** [comment]
Okay, that's fine :)  I'll commit the above `approxEq` signature.

Looking at your updated documentation for `rotateEuler`, there's still something about it and/or the implementation that needs tweaking.
1) In my implementation, although it rotates in the order of Z, Y, X, the parameters were in the order of X, Y, Z.  The order you've documented probably makes more sense, so I'll update the implementation to match it.
1) The names for the axes don't make sense.  See [this diagram](https://en.wikipedia.org/wiki/File:Yaw_Axis_Corrected.svg).  In general, "pitch" refers to swinging your view up/down, or around the right-axis (X-axis); "yaw" refers to swinging your view left/right, or around the up-axis (Y-axis); and "roll" refers to spinning your view around the forward-axis (in this case the *negative* Z-axis).
1) Given that "roll" is generally around the forward-axis, and that the Z-axis is backwards, I wonder if we should change the implementation and test property of `rotateEuler` such that ``rotateEuler roll yaw pitch `approxEq` rotateX pitch %* rotateY yaw %* rotateZ (-roll)``.

**Comment by achirkin** [comment]
Shit! Sorry, this was a Monday morning typo :) I will change the documentation now, wait pls

**Comment by Rotaerk** [comment]
~~What are your thoughts regarding comment #3 above, about negating roll?~~

Nevermind :P Based on the new documentation, it looks like you opted for the simpler (and slightly faster) option over negating the roll.  Since the documentation is clear regarding the direction of the roll, that should be fine.  The user can negate the roll if they so desire.

**Comment by achirkin** [comment]
Updated the docs.

In the diagram you showed, the coordinate system is a bit up-side-down (pitch - X, yaw - Y, roll - Z). But it is still a [right-triple](https://en.wikipedia.org/wiki/Right-hand_rule), so it makes a good illustration.

In our case Z is not really "backwards". This is just an interesting fact that the camera faces negative Z direction in 3D Computer Graphics; as all other objects on a scene, it still uses right-triple coordinate system. None of the transformations depend on where is "up" or "forward" direction, but changing the sign of one of the free unit vector flips the coordinate system to the left-triple state.

So your implementation is good as is :)

**Comment by Rotaerk** [comment]
Okay thanks, makes sense.  I'll make a final commit, including the unified approxEq, tonight.

**Comment by Rotaerk** [comment]
Well, I'm done. :) Only thing that I don't like about it is the duplication of the tests across Float and Double...  It's necessary to test both the Float and Double instances, but I don't like how the tests themselves are basically exact copies of one another.  This means that any changes to one need to be mirrored in the other.  Is there any good way to fix that?  If not, I think this is ready for a merge...

**Comment by achirkin** [comment]
The only way I could see is to replace element type with type variables in all tests and then create a new version of TemplateHaskell QuickCheck function `$quickCheckAll` that would substitute Float and Double. But that would be complicated, so I think it is better to keep two versions for now.

Well, great job! Thanks, I am merging it now

**Pull request merged**
